name: deploy-function-app

on: workflow_dispatch

env:
  AZURE_FUNCTIONAPP_NAME: "malachiscvpagecounter"
  POM_XML_DIRECTORY: "functionApp"
  POM_FUNCTIONAPP_NAME: "cvPageCounter-1618432004182"
  JAVA_VERSION: '17'

jobs:
  build_and_deploy_function_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "adopt"
      - name: Build with Maven
        run: mvn clean package --file './${{ env.POM_XML_DIRECTORY }}/pom.xml'
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.3.2
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
